### ISSUE TITLE
Cannot import repo from Mac OS X El Capitan build 15A235d (db5)

### ISSUE THREAD

**Issue by kode54** [buchuki/gitifyhg#99]
When using this command:

    git clone gitifyhg::ssh://hg@bitbucket.org/kode54/cog cog-git

I get this output immediately:

```
Cloning into 'cog-git'...
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-gitifyhg", line 9, in <module>
    load_entry_point('gitifyhg==0.8.4', 'console_scripts', 'git-remote-gitifyhg')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.macosx-10.11-intel/egg/gitifyhg/gitifyhg.py", line 42, in <module>
ImportError: cannot import name readcurrent
```

**Comment by fingolfin** [comment]
gitifyhg isn't really supported anymore. Perhaps try my fork of git-remote-hg at https://github.com/fingolfin/git-remote-hg/

**Comment by fingolfin** [comment]
(That said, I have never tested on 10.11, and so I don't know if git-remote-hg will work there, but if you report a bug for *that*, I'll look into it)
